### ISSUE TITLE
next release planning

### ISSUE THREAD

**Issue by DanielRuf** [amsul/pickadate.js#1083]
The next release will probably just be a minor release.

Which of the current PRs and issues should we address and try to bring into the next release?

cc @amsul

**Comment by elieobeid7** [comment]
My opinion is to bring all the pull requests you or @amsul approved. Skimming through them on my phone, i see that you declined many of them.

Once done lets see what issues can be fixed with minimal effort since there are so many of them . 

I love your dedication to a jQuery date picker when the creator left it and when the world is leaving jQuery for other frameworks.

**Comment by amsul** [comment]
@DanielRuf we can do a minor release from what's already in `master` so the issues that have already been merged are available on npm. Any pending PRs can come in the one after.

It also seems like we have a vulnerable dependency: https://github.com/amsul/pickadate.js/network/dependencies#package-lock.json. It'd be nice to resolve that before the release.

**Comment by DanielRuf** [comment]
> It also seems like we have a vulnerable dependency: amsul/pickadate.js/network/dependencies#package-lock.json. It'd be nice to resolve that before the release.

I do not see the warning, do you mean `hoek`?
What does `npm ls hoek` output?
