### ISSUE TITLE
Do we really need the raf polyfill?

### ISSUE THREAD

**Issue by DanielRuf** [amsul/pickadate.js#1151]
See current `future` branch.

https://caniuse.com/#feat=requestanimationframe

Also we could directly integrate it if needed. Or people could polyfill it if needed.

**Comment by amsul** [comment]
@DanielRuf we should keep these discussions over at [Spectrum](https://spectrum.chat/pickadate) (whether private DM or to the channel) considering it's not really an "issue" with the library but rather discussions/planning.

Regarding your question though, I added it as a simple polyfill so that it works across all environments (node, browser, React Native). I believe it would also make testing easier as well. I'm open to removing it if we can cover all the use cases without it.

It __*is*__ an incredibly tiny library and doesn't add significant overhead.
