### ISSUE TITLE
No value by default

### ISSUE THREAD

**Issue by jackmcdade** [amsul/pickadate.js#188]
Everything seems work okay if I actually click the field and select a date, but if i just submit a form with the default value (Which shows fine), the $_POST data for my pickadate field is null.

**Comment by calvin-smith** [comment]
I just ran into a very similar issue, where existing dates were not being filled into the form correctly on load.  Searching, I ran into this thread.  For me, the problem was not pickdate.js.  I am leaving a comment for other users who may find this thread when searching.

The issue was because of date formatting.  Dates that were posted were caught by C# and converted automatically so it worked in that direction.  Existing dates were in the incorrect format, and the date field was left empty.

The solution was to make sure that format is set to match the rest of your application.
        
format: 'yyyy-mm-dd'
