### ISSUE TITLE
Required attribute not working when pickadate.js is enabled

### ISSUE THREAD

**Issue by siamkreative** [amsul/pickadate.js#220]
Hi there,

Please run the following test case: http://jsfiddle.net/SiamKreative/qqyRA/ (try to submit the form without any date).

I think that because the plugin adds the `readonly` attribute, the form validation does not work.

What's the work around to make the form validation behave normally?

Cheers

**Comment by nevaforget** [comment]
when I set editable to true the time or datepicker doesn't appear anymore on focus, even if I doesn't set any other option. Doesn't make sense to me, so what am I doing wrong?

thanks in advance

**Comment by ssstofff** [comment]
I have the same, but I suppose this is the aim, editable, so no need to get the interface to pick the date.

Right?

**Comment by nevaforget** [comment]
This aim makes no sense. If no picker appears I don't need a picker plugin :) 

I get the point that otherwise the keyboard appears on mobile devices, but I've the point that a date field with a date picker is needed as required in 95% of all cases.

I guess something like adding/removing the readonly attr on focus/blur(submit) could work. hopefully there will be a solution in time.

best regards

**Comment by milivojsa** [comment]
My solution is to set required for dummy input then initialize picker on focus on that input. 

When you try to submit form and dummy input is not filled HTML will automatically focus that field and picker will popup.

Hope that this will help you!
All best

**Comment by shehjart** [comment]
@milivojsa Would you mind sharing the code for this please? It will make my life so much easier at this stage.

@amsul Hi!, Its been some time since @nevaforget pointed this out. Is there an easier solution that what milivojsa has proposed?

Thank you for a wonderful piece of engineering with this library.
