### ISSUE TITLE
Make pickadate work out of box with npm and browserify.

### ISSUE THREAD

**Issue by crocket** [amsul/pickadate.js#365]
pickadate doesn't work with browserify out of box.

There are steps to make it work with browserify out of box.
1. picker.js should require picker.date.js and picker.time.js. Not the other way around.
2. set "main" attribute in package.json and publish the library to npm.

**Comment by mogarick** [comment]
Hi @amsul,

The current version of pickadate as a module only exposes the instance of PickerConstructor but it doesn't expose DatePicker neither TimePicker so every time we try to instantiate a date picker or time picker we got the error `undefined is not a function` because neither of them have been loaded and so no `jquery.extend` invocation have been made to append them to the jQuery object.

@crocket tried to show the problem but he couldn't explain it clearly, as you pointed out. The dependency graph is as you said both `pick.date` and `pick.time` depend on `picker.js` not the other way around.

What is needed is some kind of facade / wrapper to expose all the pickadate functionality out of the box.

For this I made some small changes. I added an `index.js` that works as the facade / wrapper for `picker.js`, `pick.date` and `pick.time`, allowing them to be used out of the box with Browserify by issuing the typical `require('pickadate')`. It doesn't need to be assigned to a variable since pickadate attaches itself directly to the jQuery object. 

This change is a copy of the way the [CryptoJS library](https://github.com/evanvosberg/crypto-js) by @evanvosberg exposes its different algorithms through the same pattern implemented in its `index.js` file.

It would be great if this feature addition could be incorporated to the pickadate code. For that I can see this options:

1. You may check the CrytpoJS `index.js` file and create a copy for pickadate or 
2. you can check the [this gist](https://gist.github.com/mogarick/edfe96cb0a7682996c1d) with the contents for the `index.js` I created to include in pickadate or 
3. I can make a push request to integrate this feature directly.

The only additional change would be to modify the property `main` in `package.json` to point to `index.js`.

What you think? Is it possible to add this to pickadate to finally made it browserify ready out of the box? :)

Greetings and congratulations for such excellent plugin! You've made the day of many many devs outhere. :D

**Comment by ingro** [comment]
Thanks @mogarick your gists saved me a lot of time!

**Comment by cargix1** [comment]
@mogarick thanks for posting the solution above. Just in case anyone else makes the same mistake as me. I had to import the package via bower not npm. Then prepended "index.js" to the bower.json file within the package.

**Comment by ValeryIvanov** [comment]
@amsul , any way this @mogarick solution could be added to this project?

**Comment by dottodot** [comment]
The solution @mogarick has provided works well, please can it be added.
