### ISSUE TITLE
Set hidden input’s name using visible input - and remove visible input’s name

### ISSUE THREAD

**Issue by psorowka** [amsul/pickadate.js#377]
Say we have the following minimal form:

```
<form>
  <input type="date" name="the_date" />
  <input type="submit" />
</form>
```

Adding datepicker will extend this form like this:

```
<form>
  <input type="date" name="the_date" />
  <input type="hidden" name="the_date_submit" />
  <input type="submit" />
</form>
```

This forces the server-side to be kind of aware of pickadate. It also does not allow progressive enhancement. IMHO the form should be more like: 

```
<form>
  <input type="date" name="display_the_date" />
  <input type="hidden" name="the_date" />
  <input type="submit" />
</form>
```

In order to not break current behavior, adding an option 'displaySuffix' and 'displayPrefix' would be an idea. 

Also it would be cool when then suffix would respect array notation. In a rails app i usually have input names like: 

```
<input type="date" name="reservation[date]" />
```

 Appending the suffix like this:

```
<input type="date" name="reservation[date]_submit" /> 
```

breaks the form. Prefereable would be

```
<input type="date" name="reservation[date_submit]" /> 
```

Should I implement those features and drop in a pull-request?

**Comment by harmdewit** [comment]
Nice solution, seems a better solution than the hidden prefixes/suffixes. Could this please become the default? 

I can imagine this makes it harder to upgrade, but new people with ruby/rails seem to keep running into this issue because root problem is unclear, see also https://github.com/veracross/pickadate-rails/issues/13#issuecomment-176099378
