### ISSUE TITLE
Use SASS instead of LESS.

### ISSUE THREAD

**Issue by kb3eua** [amsul/pickadate.js#550]
My company's UI/UX team prefer SASS over LESS.  Can you make SASS files available with pickadate?

**Comment by graste** [comment]
SCSS flavor of SASS please. ;)

**Comment by darionato** [comment]
+1 libsass

**Comment by piehouserat** [comment]
+1 for SASS as well :)

**Comment by rdetert** [comment]
+1

**Comment by gauchomatt** [comment]
+1

**Comment by dennisfrank** [comment]
+1

**Comment by nybblr** [comment]
FWIW, I did a quick port off the latest release to SCSS on my fork: https://github.com/nybblr/pickadate.js/tree/scss not thoroughly debugged but they all compile, and I use the classic theme in production.

**Comment by jackblackCH** [comment]
+1 libsass

**Comment by atrauzzi** [comment]
+1 libsass

**Comment by jantimon** [comment]
@amsul any feedback on this? can we do sth to push this forward?

**Comment by amsul** [comment]
@jantimon we've started working on v4 now in a new branch at https://github.com/amsul/pickadate.js/tree/next

It's using CSS4 variables..and I'd like to support older browsers using [CSSNext](http://cssnext.io/).  However I haven't tried enough to know how default variables would work. I would assume natural CSS specificity would kick in and so any variable declarations *after* importing pickadate's stylesheet would take precedence. You have any experience with this?

**Comment by jantimon** [comment]
@amsul oh that sounds awful 👎 
css variables are an interesting solution but they are limited and have a very very bad browser support.
Css Next is doing a search and replace and removes the variables from the css for older browsers.

It would be way better to configure pickadate using sass default variables during build time instead of overwriting variables or styles in the browser.

**Comment by bl4ckdu5t** [comment]
@jantimon Cssnext is not doing a find and replace. It is a plugin for PostCSS which goes through an AST more like mappings rather than matching. Read more [here](https://css-tricks.com/want-make-postcss-plugin/) and [here](http://davidtheclark.com/its-time-for-everyone-to-learn-about-postcss/) . Also, the CSS level 4 is more than just cool CSS variables. With cssnext you get autoprefixing which covers cross browser cases, custom media, custom properties, nesting, color functions to say the least. But if the point is that most people that'd be using the plugin would want to extend it and Sass is a more common preprocessor (I use it mostly) then I'd say it's worth considering over PostCSS

**Comment by jantimon** [comment]
@bl4ckdu5t I know technically it's not a string search and replace but in fact it just searches for the variables using the ast and replaces the variable with a hardcoded value.

pickadate next uses flexbox anyway.. so it won't be very compatible.. don't know why you would take a very compatible datepicker which can be used without thinking about browser support and make it as incompatible as possible.

so maybe we should rather focus on using scss for pickadate 3.5 and keep flex and css variables for 2018.

**Comment by DanielRuf** [comment]
> css variables are an interesting solution but they are limited and have a very very bad browser support

This is not the case anymore.

Flexbox is also support in all current browsers.

Sass is slower than PostCSS and not an option in the future. Also Less is very simila to SCSS.
