### ISSUE TITLE
Disable dates not possible 

### ISSUE THREAD

**Issue by wernergusset** [amsul/pickadate.js#839]
Use the latest version and can not disable dates. Even on the documentation page [http://amsul.ca/pickadate.js/date/#disable-dates](url) the dates from the sample code are not disabled.
Only weekdays are possible to disable.

**Comment by AbeCole** [comment]
I just came here looking to see if anyone else had an issue and then started to investigate in the source and realised I was setting the option 'disabled' not 'disable' by mistake, so ensure you aren't doing the same. 

I can vary the disable option is working in the latest version, looking at the documentation that you mentioned it is also working there it just appears not to be because the dates are set in 2015 and the picker automatically shows the current (2016) date when opened. If you click back to 2015 you'll see it working so unfortunately if it's not working on your implementation it is something about the way you are doing it.

I believe this should be closed.

**Comment by wernergusset** [comment]
Thanks
I realize that the month count did irritate me. Yes, it works when I consider this count. But thing is, the disabled dates come from a db with dates in usual count where march is 3. Now we have to manipulate the month after reading the db with our dates. Why is the mointh count that strange?
And why can it not accept dates in the format we have defined? Like in our case it is:  format: 'dd.mm.yyyy'. Other datepickers do so.
For our project I had to take something else. But your datepicker would still be the one we like the most..

**Comment by AbeCole** [comment]
Ye I'm not sure why it takes only those date formats, although to be honest when you have to setup custom JS to use it anyway (the settings object is pretty unique to this datepicker) it isn't a lot of effort to do (date.month-1).

However I'm sure the author would love for you to implement the feature of other dates and make a pull request. Remember this is open source so if something doesn't fit you can always make the adjustment and more than likely other people will be grateful for it. (Although in this case the documentation could really do with updating to use dynamic dates so it doesn't appear broken).

Also having look at the documentation it does say this:

> NOTE: months in a JavaScript Date object are zero-indexed. Meaning, new Date(2015, 3, 20) is 20 April, 2016.

> To stay consistent with this, whenever an integer is used in reference to a month, pickadate treats it as zero-indexed. Dates as strings are still parsed as expected.

**Comment by wernergusset** [comment]
I understand what you mean. But I am not that experienced in JS to really do adjustments. I can close this for now.

**Comment by shockalotti** [comment]
You absolutely must put this in the documentation.

I imagine the cumulative lost time on "head scratching", from the many people who've struggled with this same issue, must be massive.
