### ISSUE TITLE
initial value as "yyyymmdd" not recognized?

### ISSUE THREAD

**Issue by cdsaenz** [amsul/pickadate.js#880]
I need to handle the "hidden" value of the control as "yyyymmdd" (as both initial value and also as the value returned to the server) while showing "dd/mm/yyyy" to the user. However when I set, for example `date-value='20160504'`, the initial displayed format reverts to 01/01/1970..  

Can this be accomplished?

Relevant Code:

`<input
          id="input_01" class="datepicker" value="20140808"
          name="dtp" type="text" data-value="20140808">`

and

`var $input = $( '.datepicker' ).pickadate({
            format: 'dd/mm/yyyy',
            formatSubmit: 'yyyymmdd',
            container: '#container',
            closeOnSelect: false,
            closeOnClear: false,
        })
`

**Comment by joraff** [comment]
Seems it depends on what type of object the javascript interpreter thinks data-value is. In this case, a `yyyymmdd` format can be a true number, and my browser was casting it as such. Pickadate's parser is expecting only a string. Adding a `'' + num` in `picker.date.js` fixed my case.

**Comment by amsul** [comment]
@cdsaenz That's a very dangerous pattern to follow. You should **always** have delimiters in between the formatting units otherwise it's difficult to assert with 100% certainty that it was parsed correctly (for instance if the format is `yyyymd` and the value is 2014112). 

For that reason, this isn't and won't be supported.

**Comment by joraff** [comment]
@amsul I think the parsability of a format one chooses to use is their own problem. I agree that delimiters are great insurance against misformatted data, but I also do work elsewhere to ensure my dates are formatted accurately.

There may be some valid reasons to use numbers over delimited strings. For example, I am using integers because they're faster to sort and filter.

My simple proposed fix would do nothing to the parser except bring more objects to it. It should have no effect on delimited formats.

**Comment by amsul** [comment]
@joraff consider it saving developers from themselves 😉 .

Besides, sorting should be done by the actual date time, not the formatted date. I don't see any good reason why delimiters would not be used.
