### ISSUE TITLE
Change today date to a fixed date

### ISSUE THREAD

**Issue by avlima** [amsul/pickadate.js#907]
Hello, I am trying to change the client's default date for a date server, I am using the .set method ('select', date), it is yes selected the date that I set, however today's date he still takes the client. I would like to change the date today too?

This is my example:
![todaypickadate](https://cloud.githubusercontent.com/assets/13434925/18105813/44a2be4a-6ed7-11e6-8dbb-271d27e8fdf4.jpg)

**Comment by Jivebunny** [comment]
@avlima Maybe some more info by showing us what you're code to achieve this is?

**Comment by avlima** [comment]
@Jivebunny  After waiting months I could no longer wait for help and decided by own account, not as I would like but the way I found solved my problem.

**Comment by rolandfung** [comment]
I'm interested in manually setting "today" (.picker__day--today, the day with the little blue arrow in the corner) since my project's business requirements state that the calendar should always appear as if it's in the client's timezone, no matter where the browser is located. Is there a way in the API to override "today"/"now"?
